language: python
dist: xenial

before_install:
  - sudo apt-get install -y python-virtualenv
  - virtualenv planemo-venv
  - . planemo-venv/bin/activate
  - pip install planemo==0.58.1
  - planemo conda_init

install:
  - planemo conda_install ${TRAVIS_BUILD_DIR}

script:
  - planemo lint ${TRAVIS_BUILD_DIR}
  - planemo test --conda_debug --no_cache_galaxy --galaxy_branch release_18.05 --file_path ${TRAVIS_BUILD_DIR} --job_output_files ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_DIR}

after_script:
  - ls ${TRAVIS_BUILD_DIR}
  - cat tool_test_output.json